language: node_js
node_js:
  - node

dist: bionic
sudo: required

branches:
  only:
   - master

before_script:
  - cd ./client/
  - npm install -g @angular/cli

script:
  - cd ./client/
  - ng build --prod --base-href https://yekai7.github.io/swap/

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist/swap
  on:
    branch: master

notifications:
  email:
    recipients:
      - yekai7@hotmail.com
    on_failure: always